terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# Generate SSH Key Pair for Ansible
resource "tls_private_key" "ansible" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "ansible" {
  key_name   = "${var.project_name}-key"
  public_key = tls_private_key.ansible.public_key_openssh

  tags = {
    Name = "${var.project_name}-key"
  }
}

# Save private key locally
resource "local_file" "private_key" {
  content         = tls_private_key.ansible.private_key_pem
  filename        = "${path.module}/hajar-project-key.pem"
  file_permission = "0600"
}

# Auto-generate Ansible inventory file
resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../ansible/inventory/hosts.yml"
  content  = <<-EOT
    # =============================================================================
    # ANSIBLE INVENTORY - Auto-generated by Terraform
    # =============================================================================
    # Run 'terraform apply' to regenerate this file with updated IPs
    # =============================================================================

    all:
      children:
        zeppelin:
          hosts:
            zeppelin-server:
              ansible_host: "${module.compute.zeppelin_public_ip}"
              # Private IP for Spark driver callbacks (within VPC)
              zeppelin_private_ip: "${module.compute.zeppelin_private_ip}"
        
        spark:
          hosts:
            spark-server:
              ansible_host: "${module.compute.spark_private_ip}"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/hajar-project-key.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@${module.compute.zeppelin_public_ip}"'
        
        neo4j:
          hosts:
            neo4j-server:
              ansible_host: "${module.neo4j.private_ip}"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/hajar-project-key.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@${module.compute.zeppelin_public_ip}"'
        
        private:
          children:
            spark:
            neo4j:
        
        compute:
          children:
            zeppelin:
            spark:
            neo4j:

      vars:
        ansible_user: ubuntu
        ansible_python_interpreter: /usr/bin/python3
        # SSH key in WSL home directory (NTFS doesn't support proper Linux permissions)
        ansible_ssh_private_key_file: "~/hajar-project-key.pem"
  EOT

  depends_on = [
    module.compute,
    module.neo4j
  ]
}

# Network module
module "network" {
  source = "./modules/network"

  project_name         = var.project_name
  vpc_cidr             = var.vpc_cidr
  public_subnet_cidr   = var.public_subnet_cidr
  public_subnet_2_cidr = var.public_subnet_2_cidr
  private_subnet_cidr  = var.private_subnet_cidr
  availability_zone    = var.availability_zone
  availability_zone_2  = var.availability_zone_2
}

# S3 module
module "s3" {
  source = "./modules/s3"

  project_name = var.project_name
  vpc_id       = module.network.vpc_id
  route_table_id = module.network.private_route_table_id
}

# IAM module
module "iam" {
  source = "./modules/iam"

  project_name = var.project_name
  s3_bucket_arn = module.s3.bucket_arn
}

# Compute module (Zeppelin + Spark)
module "compute" {
  source = "./modules/compute"

  project_name          = var.project_name
  ami_id                = var.ami_id
  zeppelin_instance_type = var.zeppelin_instance_type
  spark_instance_type   = var.spark_instance_type
  zeppelin_volume_size  = var.zeppelin_volume_size
  spark_volume_size     = var.spark_volume_size
  
  public_subnet_id      = module.network.public_subnet_1_id
  private_subnet_id     = module.network.private_subnet_id
  
  zeppelin_sg_id        = module.alb.zeppelin_sg_id
  spark_sg_id           = module.network.spark_sg_id
  
  iam_instance_profile  = module.iam.instance_profile_name
  key_name              = aws_key_pair.ansible.key_name
}

# Neo4j module
module "neo4j" {
  source = "./modules/neo4j"

  project_name         = var.project_name
  ami_id               = var.ami_id
  instance_type        = var.neo4j_instance_type
  volume_size          = var.neo4j_volume_size
  private_subnet_id    = module.network.private_subnet_id
  security_group_id    = module.network.neo4j_sg_id
  iam_instance_profile = module.iam.instance_profile_name
  key_name             = aws_key_pair.ansible.key_name
}

# ALB module
module "alb" {
  source = "./modules/alb"

  project_name          = var.project_name
  vpc_id                = module.network.vpc_id
  public_subnet_1_id    = module.network.public_subnet_1_id
  public_subnet_2_id    = module.network.public_subnet_2_id
  private_subnet_cidr   = var.private_subnet_cidr
  acm_certificate_arn   = var.acm_certificate_arn
  allowed_cidr_blocks   = var.allowed_cidr_blocks
  zeppelin_instance_id  = module.compute.zeppelin_instance_id
}

# Monitoring module
module "monitoring" {
  source = "./modules/monitoring"

  project_name = var.project_name
}
