#!/bin/bash
# =============================================================================
# Setup Ansible Inventory from Terraform Outputs
# =============================================================================
# Run this script after `terraform apply` to automatically configure Ansible
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../terraform"
ANSIBLE_DIR="$SCRIPT_DIR"

echo "======================================"
echo "  Setting up Ansible for Hajar Project"
echo "======================================"

# Check if terraform outputs exist
cd "$TERRAFORM_DIR"

echo ""
echo "📡 Getting IPs from Terraform..."

ZEPPELIN_IP=$(terraform output -raw zeppelin_public_ip 2>/dev/null || echo "")
SPARK_IP=$(terraform output -raw spark_private_ip 2>/dev/null || echo "")
NEO4J_IP=$(terraform output -raw neo4j_private_ip 2>/dev/null || echo "")

if [ -z "$ZEPPELIN_IP" ] || [ -z "$SPARK_IP" ] || [ -z "$NEO4J_IP" ]; then
    echo "❌ Error: Could not get IPs from Terraform."
    echo "   Make sure you have run 'terraform apply' first."
    exit 1
fi

echo "  ✅ Zeppelin: $ZEPPELIN_IP"
echo "  ✅ Spark: $SPARK_IP"
echo "  ✅ Neo4j: $NEO4J_IP"

# Update inventory file
echo ""
echo "📝 Updating Ansible inventory..."

cat > "$ANSIBLE_DIR/inventory/hosts.yml" << EOF
# =============================================================================
# ANSIBLE INVENTORY - Auto-generated by setup-inventory.sh
# =============================================================================
# Generated on: $(date)
# =============================================================================

all:
  children:
    zeppelin:
      hosts:
        zeppelin-server:
          ansible_host: "$ZEPPELIN_IP"
    
    spark:
      hosts:
        spark-server:
          ansible_host: "$SPARK_IP"
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@$ZEPPELIN_IP'
    
    neo4j:
      hosts:
        neo4j-server:
          ansible_host: "$NEO4J_IP"
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@$ZEPPELIN_IP'
    
    private:
      children:
        spark:
        neo4j:
    
    compute:
      children:
        zeppelin:
        spark:
        neo4j:

  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
EOF

echo "  ✅ Inventory updated!"

# Copy SSH key if needed
echo ""
echo "🔑 Setting up SSH key..."

SSH_KEY="$TERRAFORM_DIR/hajar-project-key.pem"
if [ -f "$SSH_KEY" ]; then
    chmod 600 "$SSH_KEY"
    echo "  ✅ SSH key found and permissions set!"
else
    echo "  ❌ SSH key not found at $SSH_KEY"
    exit 1
fi

# Test SSH connection
echo ""
echo "🔗 Testing SSH connection to Zeppelin..."

if ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=10 ubuntu@$ZEPPELIN_IP "echo 'SSH OK'" 2>/dev/null; then
    echo "  ✅ SSH connection successful!"
else
    echo "  ⚠️  SSH connection failed. Instance might still be booting..."
    echo "      Wait 1-2 minutes and try again."
fi

# Create secrets file if not exists
if [ ! -f "$ANSIBLE_DIR/variables/secrets.yml" ]; then
    echo ""
    echo "🔐 Creating secrets file..."
    cat > "$ANSIBLE_DIR/variables/secrets.yml" << EOF
---
# Neo4j admin password
neo4j_admin_password: "bath123@@"
EOF
    echo "  ✅ Created secrets.yml (update the password!)"
fi

echo ""
echo "======================================"
echo "  ✅ Setup Complete!"
echo "======================================"
echo ""
echo "Next steps:"
echo "  1. Edit secrets: nano $ANSIBLE_DIR/variables/secrets.yml"
echo "  2. Run Ansible:  cd $ANSIBLE_DIR && ansible-playbook playbooks/site.yml"
echo ""
